### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by BlueWhaleYT** [hachkingtohach1/TeamArena#1]
Hey there, I am surprise that someone made a plugin TeamArena. However, maybe I am little bit silly to the setup instruction. I got an error after I clicked the join sign.

`[Server thread/CRITICAL]: Error: "Call to a member function getProvider() on null" (EXCEPTION) in "plugins/TeamArena.phar/src/hachkingtohach1/teamarena/task/ArenaScheduler" at line 46`

Thanks.

**Comment by hachkingtohach1** [comment]
You need install plugins: EconomyAPI, KillCounter, thanks for downloading :@@

**Comment by BlueWhaleYT** [comment]
But I.... installed them already...
:(
