### ISSUE TITLE
[Suggestion] - Scoreboard support?

### ISSUE THREAD

**Issue by BlueWhaleYT** [hachkingtohach1/TeamArena#2]
Hey there, will this plugin supports Scoreboard to show the game stats? Due to the fact that the popups don't perform well actually and displaying stats with Scoreboard is better cleaning maybe.

(This is a suggestion only) ty

(This text is a off-topic of this issue, after I installed your repo KillCounter, it did well) ty

**Comment by hachkingtohach1** [comment]
hmm be thankful I will think!
